server:
  port: 8081 #服务器端口

spring:
  datasource: #数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scdb?characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: chenyj
    password: chenyj
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis: #redis配置
    host: localhost
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 60

management: #Actuator配置
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: health,hystrix.stream #允许暴露的端点
      base-path: /
  endpoint:
    health:
      show-details: always
